name: CICD

on:
  push:
    branches: [gcp-app-engine]
    
jobs:
  build:
    runs-on: [ubuntu-latest]
    permissions:
     contents: 'read'
     id-token: 'write'
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Dependencies
        run : npm install
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  
